AUG:
  MEAN:
  - 0.4712
  - 0.4499
  - 0.4031
  STD:
  - 0.2726
  - 0.2634
  - 0.2794
  TEST_CROP: true
DATA:
  IMG_SIZE: 84
  NUM_WORKERS: 8
  TEST:
    BATCH_SIZE: 1
    DATASET_NAMES:
    - miniImageNet
    DATASET_ROOTS:
    - /data1/jiangzhen/fzy/dataset/miniImageNet/
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 15
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 15
      NUM_SUPPORT: 1
      NUM_TASKS_PER_EPOCH: 100
      NUM_WAYS: 5
      SEQUENTIAL_SAMPLING: 1
      USE_BILEVEL_HIERARCHY: false
      USE_DAG_HIERARCHY: false
GPU_ID: 0
IS_TRAIN: 0
MODEL:
  BACKBONE: resnet12
  CLASSIFIER: proto_knn_head
  NAME: PNNLP_mini_1-shot
  PRETRAINED: /data1/jiangzhen/fzy/PKNNLP_last/evaluation/mini_1-shot/ckpt_epoch_0_top1.pth
  TYPE: Episodic_Model_knn
OUTPUT: ./new_metadataset_result
