
DATA:
  IMG_SIZE: 84
  NUM_WORKERS: 8
  TRAIN:
    BATCH_SIZE: 2
    DATASET_NAMES:
    - CIFAR100
    DATASET_ROOTS:
    - /data/jz/fzy/dataset/cifar100/
    EPISODE_DESCR_CONFIG:
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 15
      NUM_SUPPORT: 5
      NUM_TASKS_PER_EPOCH: 1000
      NUM_WAYS: 5
      USE_DAG_HIERARCHY: false
    IS_EPISODIC: true
  VALID:
    BATCH_SIZE: 8
    DATASET_NAMES:
    - CIFAR100
    DATASET_ROOTS:
    - /data/jz/fzy/dataset/cifar100/
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 15
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 15
      NUM_SUPPORT: 5
      NUM_TASKS_PER_EPOCH: 600
      NUM_WAYS: 5
      USE_DAG_HIERARCHY: false
GPU_ID: 0
MODEL:
  BACKBONE: resnet12
  CLASSIFIER: proto_knn_head
  NAME: cifar100_Res12_PNKNN_5way-5shot
  TYPE: Episodic_Model_knn
OUTPUT: /data/jz/fzy/CloserLookAgainFewShot-master/
TRAIN:
  BASE_LR: 0.05
  EPOCHS: 80
