AUG:
  MEAN:
  - 0.4712
  - 0.4499
  - 0.4031
  STD:
  - 0.2726
  - 0.2634
  - 0.2794
DATA:
  IMG_SIZE: 84
  NUM_WORKERS: 8
  TRAIN:
    BATCH_SIZE: 2
    DATASET_NAMES:
    - miniImageNet
    DATASET_ROOTS:
    - /data1/mazc/fzy/dataset/miniImageNet/
    EPISODE_DESCR_CONFIG:
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 15
      NUM_SUPPORT: 1
      NUM_TASKS_PER_EPOCH: 1000
      NUM_WAYS: 5
      USE_DAG_HIERARCHY: false
    IS_EPISODIC: true
  VALID:
    BATCH_SIZE: 8
    DATASET_NAMES:
    - miniImageNet
    DATASET_ROOTS:
    - /data1/mazc/fzy/dataset/miniImageNet/
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 15
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 15
      NUM_SUPPORT: 1
      NUM_TASKS_PER_EPOCH: 600
      NUM_WAYS: 5
      USE_DAG_HIERARCHY: false
GPU_ID: 0

MODEL:
  BACKBONE: resnet12
  CLASSIFIER: proto_knn_head
  NAME: mini_Res12_PNKNN_5way-1shot
  TYPE: Episodic_Model_knn
OUTPUT: /data1/mazc/fzy/115-result/miniImagenet/PKNN-res12/
TRAIN:
  BASE_LR: 0.05
  EPOCHS: 80
